### ISSUE TITLE
Deprecated use of clip_upper

### ISSUE THREAD

**Issue by GeneralPoxter** [Pinafore/qb#93]
Running GuesserReport task results in the following error:
```
ERROR: [pid 20340] Worker Worker(salt=313169456, workers=1, host=poxter, username=poxter, pid=20340) failed    GuesserReport(guesser_module=qanta.guesser.rnn, guesser_class=RnnGuesser, dependency_module=qanta.pipeline.guesser, dependency_class=EmptyTask, config_num=0, fold=guessdev)
Traceback (most recent call last):
  File "/home/poxter/.cache/pypoetry/virtualenvs/qanta-virId68h-py3.9/lib/python3.9/site-packages/luigi/worker.py", line 191, in run
    new_deps = self._run_get_new_deps()
  File "/home/poxter/.cache/pypoetry/virtualenvs/qanta-virId68h-py3.9/lib/python3.9/site-packages/luigi/worker.py", line 133, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/poxter/qb/qanta/pipeline/guesser.py", line 226, in run
    guesser_instance.create_report(guesser_directory, self.fold)
  File "/home/poxter/qb/qanta/guesser/abstract.py", line 372, in create_report
    char_df["char_percent"] = (
  File "/home/poxter/.cache/pypoetry/virtualenvs/qanta-virId68h-py3.9/lib/python3.9/site-packages/pandas/core/generic.py", line 5141, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'clip_upper'
```
According to [documentation](https://pandas.pydata.org/pandas-docs/version/0.24.2/reference/api/pandas.Series.clip_upper.html), `clip_upper(0.1)` is deprecated for the version of pandas specified in the pyproject.toml. I submitted pull request changing it to `clip(upper=1.0)`, which fixes the issue on my end.

**Comment by GeneralPoxter** [comment]
Pull request merged.
